/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PostPublic {
  'id' : bigint,
  'deleted' : boolean,
  'content' : string,
  'authorId' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'imageUrl' : [] | [string],
  'flagged' : boolean,
}
export interface UserPublic {
  'bio' : string,
  'username' : string,
  'createdAt' : bigint,
  'avatarUrl' : string,
  'isAdmin' : boolean,
  'principalId' : string,
}
export interface _SERVICE {
  'createPost' : ActorMethod<[string, [] | [string]], PostPublic>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'editPost' : ActorMethod<[bigint, string, [] | [string]], PostPublic>,
  'flagPost' : ActorMethod<[bigint], undefined>,
  'getAllPostsAdmin' : ActorMethod<[], Array<PostPublic>>,
  'getFlaggedPosts' : ActorMethod<[], Array<PostPublic>>,
  'getPost' : ActorMethod<[bigint], [] | [PostPublic]>,
  'getPosts' : ActorMethod<[bigint, bigint], Array<PostPublic>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserPublic]>,
  'getUsers' : ActorMethod<[], Array<UserPublic>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'registerOrGetUser' : ActorMethod<[], UserPublic>,
  'unflagPost' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<[string, string, string], UserPublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];