/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostPublic = IDL.Record({
  'id' : IDL.Nat,
  'deleted' : IDL.Bool,
  'content' : IDL.Text,
  'authorId' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'flagged' : IDL.Bool,
});
export const UserPublic = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'avatarUrl' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'principalId' : IDL.Text,
});

export const idlService = IDL.Service({
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [PostPublic], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'editPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [PostPublic],
      [],
    ),
  'flagPost' : IDL.Func([IDL.Nat], [], []),
  'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(PostPublic)], ['query']),
  'getFlaggedPosts' : IDL.Func([], [IDL.Vec(PostPublic)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(PostPublic)], ['query']),
  'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(PostPublic)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerOrGetUser' : IDL.Func([], [UserPublic], []),
  'unflagPost' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [UserPublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostPublic = IDL.Record({
    'id' : IDL.Nat,
    'deleted' : IDL.Bool,
    'content' : IDL.Text,
    'authorId' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'flagged' : IDL.Bool,
  });
  const UserPublic = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'avatarUrl' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'principalId' : IDL.Text,
  });
  
  return IDL.Service({
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [PostPublic], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'editPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [PostPublic],
        [],
      ),
    'flagPost' : IDL.Func([IDL.Nat], [], []),
    'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(PostPublic)], ['query']),
    'getFlaggedPosts' : IDL.Func([], [IDL.Vec(PostPublic)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(PostPublic)], ['query']),
    'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(PostPublic)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerOrGetUser' : IDL.Func([], [UserPublic], []),
    'unflagPost' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [UserPublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };