/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface PaywallLink {
    url: string;
    description: string;
    isActive: boolean;
    price: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface Tip {
    transactionHash: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
    tokenType: string;
    amount: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Wallet {
    balance: bigint;
    accountId: string;
    owner: Principal;
    transactionHistory: Array<Tip>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Post {
    id: bigint;
    categories: Array<string>;
    media: Array<ExternalBlob>;
    likeCount: bigint;
    content: string;
    reportCount: bigint;
    ratingCount: bigint;
    tags: Array<string>;
    tips: Array<Tip>;
    paywalledVideos: Array<PaywalledVideo>;
    author: Principal;
    links: Array<string>;
    averageRating: number;
    fileNames: Array<string>;
    timestamp: Time;
    commentCount: bigint;
    reported: boolean;
    flagged: boolean;
    publicVideos: Array<ExternalBlob>;
    paywallLinks: Array<PaywallLink>;
}
export interface PaywalledVideo {
    blob: ExternalBlob;
    description: string;
    isActive: boolean;
    price: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface PostUpdatePayload {
    categories?: Array<string>;
    removeMedia?: Array<ExternalBlob>;
    updatePaywalledVideos?: Array<{
        paywalledVideos: Array<PaywalledVideo>;
        description?: string;
        isActive?: boolean;
        price?: bigint;
    }>;
    content?: string;
    removePublicVideos?: Array<ExternalBlob>;
    reportReason?: string;
    removePaywallLinks?: Array<string>;
    removePaywalledVideos?: Array<ExternalBlob>;
    tags?: Array<string>;
    addPublicVideos?: Array<ExternalBlob>;
    updatePaywallLinks?: Array<{
        description?: string;
        isActive?: boolean;
        price?: bigint;
        paywallLinks: Array<PaywallLink>;
    }>;
    removeLinks?: Array<string>;
    addPaywallLinks?: Array<PaywallLink>;
    addMedia?: Array<ExternalBlob>;
    reportCategory?: string;
    addFileNames?: Array<string>;
    flagPost?: boolean;
    addPaywalledVideos?: Array<PaywalledVideo>;
    removeFileNames?: Array<string>;
    addLinks?: Array<string>;
}
export interface UserProfile {
    bio: string;
    totalRatings: bigint;
    newsletterSubscribed: boolean;
    accountId: string;
    name: string;
    averageRating: number;
    joinedDate: Time;
    followerCount: bigint;
    followingCount: bigint;
    profilePicture?: ExternalBlob;
    principalId: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addToken(canisterId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanUpReports(): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPost(content: string, media: Array<ExternalBlob>, links: Array<string>, tags: Array<string>, categories: Array<string>, fileNames: Array<string>): Promise<Post>;
    deletePost(postId: bigint): Promise<void>;
    ensureWalletExists(): Promise<void>;
    flagPost(postId: bigint): Promise<void>;
    getAccountId(): Promise<string>;
    getAdminPosts(): Promise<Array<Post>>;
    getAllPosts(): Promise<Array<Post>>;
    getBlob(blob: ExternalBlob): Promise<Uint8Array | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getImportedTokens(): Promise<Array<string>>;
    getPost(postId: bigint): Promise<Post>;
    getPostById(postId: bigint): Promise<Post>;
    getPostsByAuthor(author: Principal): Promise<Array<Post>>;
    getPostsByCategory(category: string): Promise<Array<Post>>;
    getPostsByMediaType(mediaType: string): Promise<Array<Post>>;
    getPostsByPaywallStatus(hasPaywall: boolean): Promise<Array<Post>>;
    getPostsByTags(tags: Array<string>): Promise<Array<Post>>;
    getReportedPosts(): Promise<Array<Post>>;
    getSortedReportedPosts(): Promise<Array<Post>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWallet(): Promise<Wallet>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    removeToken(canisterId: string): Promise<void>;
    reportPost(postId: bigint, category: string, reason: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPosts(searchTerm: string, includeFlagged: boolean, includeReported: boolean): Promise<Array<Post>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unflagPost(postId: bigint): Promise<void>;
    updatePost(postId: bigint, payload: PostUpdatePayload): Promise<Post>;
    uploadBlob(data: Uint8Array): Promise<ExternalBlob>;
    uploadBlobWithName(data: Uint8Array, fileName: string): Promise<ExternalBlob>;
}
import type { ApprovalStatus as _ApprovalStatus, ExternalBlob as _ExternalBlob, PaywallLink as _PaywallLink, PaywalledVideo as _PaywalledVideo, Post as _Post, PostUpdatePayload as _PostUpdatePayload, StripeSessionStatus as _StripeSessionStatus, Time as _Time, Tip as _Tip, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addToken(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToken(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async cleanUpReports(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanUpReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanUpReports();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPost(arg0: string, arg1: Array<ExternalBlob>, arg2: Array<string>, arg3: Array<string>, arg4: Array<string>, arg5: Array<string>): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, await to_candid_vec_n10(this.uploadFile, this.downloadFile, arg1), arg2, arg3, arg4, arg5);
                return from_candid_Post_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, await to_candid_vec_n10(this.uploadFile, this.downloadFile, arg1), arg2, arg3, arg4, arg5);
            return from_candid_Post_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async ensureWalletExists(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ensureWalletExists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ensureWalletExists();
            return result;
        }
    }
    async flagPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagPost(arg0);
            return result;
        }
    }
    async getAccountId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountId();
            return result;
        }
    }
    async getAdminPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPosts();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPosts();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBlob(arg0: ExternalBlob): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlob(await to_candid_ExternalBlob_n11(this.uploadFile, this.downloadFile, arg0));
                return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlob(await to_candid_ExternalBlob_n11(this.uploadFile, this.downloadFile, arg0));
            return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getImportedTokens(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImportedTokens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImportedTokens();
            return result;
        }
    }
    async getPost(arg0: bigint): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_Post_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_Post_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPostById(arg0: bigint): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostById(arg0);
                return from_candid_Post_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostById(arg0);
            return from_candid_Post_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPostsByAuthor(arg0: Principal): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByAuthor(arg0);
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByAuthor(arg0);
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPostsByCategory(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByCategory(arg0);
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByCategory(arg0);
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPostsByMediaType(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByMediaType(arg0);
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByMediaType(arg0);
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPostsByPaywallStatus(arg0: boolean): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByPaywallStatus(arg0);
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByPaywallStatus(arg0);
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPostsByTags(arg0: Array<string>): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByTags(arg0);
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByTags(arg0);
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getReportedPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportedPosts();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportedPosts();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSortedReportedPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedReportedPosts();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedReportedPosts();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWallet(): Promise<Wallet> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async removeToken(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeToken(arg0);
            return result;
        }
    }
    async reportPost(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportPost(arg0, arg1, arg2);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n36(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n36(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async searchPosts(arg0: string, arg1: boolean, arg2: boolean): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPosts(arg0, arg1, arg2);
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPosts(arg0, arg1, arg2);
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n38(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n38(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unflagPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unflagPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unflagPost(arg0);
            return result;
        }
    }
    async updatePost(arg0: bigint, arg1: PostUpdatePayload): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(arg0, await to_candid_PostUpdatePayload_n40(this.uploadFile, this.downloadFile, arg1));
                return from_candid_Post_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(arg0, await to_candid_PostUpdatePayload_n40(this.uploadFile, this.downloadFile, arg1));
            return from_candid_Post_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async uploadBlob(arg0: Uint8Array): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBlob(arg0);
                return from_candid_ExternalBlob_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBlob(arg0);
            return from_candid_ExternalBlob_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async uploadBlobWithName(arg0: Uint8Array, arg1: string): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBlobWithName(arg0, arg1);
                return from_candid_ExternalBlob_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBlobWithName(arg0, arg1);
            return from_candid_ExternalBlob_n15(this.uploadFile, this.downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n35(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_PaywalledVideo_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaywalledVideo): Promise<PaywalledVideo> {
    return await from_candid_record_n18(uploadFile, downloadFile, value);
}
async function from_candid_Post_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n13(uploadFile, downloadFile, value);
}
function from_candid_StripeSessionStatus_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n28(uploadFile, downloadFile, value);
}
function from_candid_UserApprovalInfo_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n33(uploadFile, downloadFile, value);
}
async function from_candid_UserProfile_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n23(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n22(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n15(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    categories: Array<string>;
    media: Array<_ExternalBlob>;
    likeCount: bigint;
    content: string;
    reportCount: bigint;
    ratingCount: bigint;
    tags: Array<string>;
    tips: Array<_Tip>;
    paywalledVideos: Array<_PaywalledVideo>;
    author: Principal;
    links: Array<string>;
    averageRating: number;
    fileNames: Array<string>;
    timestamp: _Time;
    commentCount: bigint;
    reported: boolean;
    flagged: boolean;
    publicVideos: Array<_ExternalBlob>;
    paywallLinks: Array<_PaywallLink>;
}): Promise<{
    id: bigint;
    categories: Array<string>;
    media: Array<ExternalBlob>;
    likeCount: bigint;
    content: string;
    reportCount: bigint;
    ratingCount: bigint;
    tags: Array<string>;
    tips: Array<Tip>;
    paywalledVideos: Array<PaywalledVideo>;
    author: Principal;
    links: Array<string>;
    averageRating: number;
    fileNames: Array<string>;
    timestamp: Time;
    commentCount: bigint;
    reported: boolean;
    flagged: boolean;
    publicVideos: Array<ExternalBlob>;
    paywallLinks: Array<PaywallLink>;
}> {
    return {
        id: value.id,
        categories: value.categories,
        media: await from_candid_vec_n14(uploadFile, downloadFile, value.media),
        likeCount: value.likeCount,
        content: value.content,
        reportCount: value.reportCount,
        ratingCount: value.ratingCount,
        tags: value.tags,
        tips: value.tips,
        paywalledVideos: await from_candid_vec_n16(uploadFile, downloadFile, value.paywalledVideos),
        author: value.author,
        links: value.links,
        averageRating: value.averageRating,
        fileNames: value.fileNames,
        timestamp: value.timestamp,
        commentCount: value.commentCount,
        reported: value.reported,
        flagged: value.flagged,
        publicVideos: await from_candid_vec_n14(uploadFile, downloadFile, value.publicVideos),
        paywallLinks: value.paywallLinks
    };
}
async function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    description: string;
    isActive: boolean;
    price: bigint;
}): Promise<{
    blob: ExternalBlob;
    description: string;
    isActive: boolean;
    price: bigint;
}> {
    return {
        blob: await from_candid_ExternalBlob_n15(uploadFile, downloadFile, value.blob),
        description: value.description,
        isActive: value.isActive,
        price: value.price
    };
}
async function from_candid_record_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    totalRatings: bigint;
    newsletterSubscribed: boolean;
    accountId: string;
    name: string;
    averageRating: number;
    joinedDate: _Time;
    followerCount: bigint;
    followingCount: bigint;
    profilePicture: [] | [_ExternalBlob];
    principalId: string;
}): Promise<{
    bio: string;
    totalRatings: bigint;
    newsletterSubscribed: boolean;
    accountId: string;
    name: string;
    averageRating: number;
    joinedDate: Time;
    followerCount: bigint;
    followingCount: bigint;
    profilePicture?: ExternalBlob;
    principalId: string;
}> {
    return {
        bio: value.bio,
        totalRatings: value.totalRatings,
        newsletterSubscribed: value.newsletterSubscribed,
        accountId: value.accountId,
        name: value.name,
        averageRating: value.averageRating,
        joinedDate: value.joinedDate,
        followerCount: value.followerCount,
        followingCount: value.followingCount,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n24(uploadFile, downloadFile, value.profilePicture)),
        principalId: value.principalId
    };
}
function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n30(uploadFile, downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n34(uploadFile, downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n29(uploadFile, downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n15(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaywalledVideo>): Promise<Array<PaywalledVideo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PaywalledVideo_n17(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n12(uploadFile, downloadFile, x)));
}
function from_candid_vec_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n32(uploadFile, downloadFile, x));
}
function to_candid_ApprovalStatus_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n39(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_PaywalledVideo_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaywalledVideo): Promise<_PaywalledVideo> {
    return await to_candid_record_n46(uploadFile, downloadFile, value);
}
async function to_candid_PostUpdatePayload_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostUpdatePayload): Promise<_PostUpdatePayload> {
    return await to_candid_record_n41(uploadFile, downloadFile, value);
}
async function to_candid_UserProfile_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n37(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    totalRatings: bigint;
    newsletterSubscribed: boolean;
    accountId: string;
    name: string;
    averageRating: number;
    joinedDate: Time;
    followerCount: bigint;
    followingCount: bigint;
    profilePicture?: ExternalBlob;
    principalId: string;
}): Promise<{
    bio: string;
    totalRatings: bigint;
    newsletterSubscribed: boolean;
    accountId: string;
    name: string;
    averageRating: number;
    joinedDate: _Time;
    followerCount: bigint;
    followingCount: bigint;
    profilePicture: [] | [_ExternalBlob];
    principalId: string;
}> {
    return {
        bio: value.bio,
        totalRatings: value.totalRatings,
        newsletterSubscribed: value.newsletterSubscribed,
        accountId: value.accountId,
        name: value.name,
        averageRating: value.averageRating,
        joinedDate: value.joinedDate,
        followerCount: value.followerCount,
        followingCount: value.followingCount,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value.profilePicture)) : candid_none(),
        principalId: value.principalId
    };
}
async function to_candid_record_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories?: Array<string>;
    removeMedia?: Array<ExternalBlob>;
    updatePaywalledVideos?: Array<{
        paywalledVideos: Array<PaywalledVideo>;
        description?: string;
        isActive?: boolean;
        price?: bigint;
    }>;
    content?: string;
    removePublicVideos?: Array<ExternalBlob>;
    reportReason?: string;
    removePaywallLinks?: Array<string>;
    removePaywalledVideos?: Array<ExternalBlob>;
    tags?: Array<string>;
    addPublicVideos?: Array<ExternalBlob>;
    updatePaywallLinks?: Array<{
        description?: string;
        isActive?: boolean;
        price?: bigint;
        paywallLinks: Array<PaywallLink>;
    }>;
    removeLinks?: Array<string>;
    addPaywallLinks?: Array<PaywallLink>;
    addMedia?: Array<ExternalBlob>;
    reportCategory?: string;
    addFileNames?: Array<string>;
    flagPost?: boolean;
    addPaywalledVideos?: Array<PaywalledVideo>;
    removeFileNames?: Array<string>;
    addLinks?: Array<string>;
}): Promise<{
    categories: [] | [Array<string>];
    removeMedia: [] | [Array<_ExternalBlob>];
    updatePaywalledVideos: [] | [Array<{
            paywalledVideos: Array<_PaywalledVideo>;
            description: [] | [string];
            isActive: [] | [boolean];
            price: [] | [bigint];
        }>];
    content: [] | [string];
    removePublicVideos: [] | [Array<_ExternalBlob>];
    reportReason: [] | [string];
    removePaywallLinks: [] | [Array<string>];
    removePaywalledVideos: [] | [Array<_ExternalBlob>];
    tags: [] | [Array<string>];
    addPublicVideos: [] | [Array<_ExternalBlob>];
    updatePaywallLinks: [] | [Array<{
            description: [] | [string];
            isActive: [] | [boolean];
            price: [] | [bigint];
            paywallLinks: Array<_PaywallLink>;
        }>];
    removeLinks: [] | [Array<string>];
    addPaywallLinks: [] | [Array<_PaywallLink>];
    addMedia: [] | [Array<_ExternalBlob>];
    reportCategory: [] | [string];
    addFileNames: [] | [Array<string>];
    flagPost: [] | [boolean];
    addPaywalledVideos: [] | [Array<_PaywalledVideo>];
    removeFileNames: [] | [Array<string>];
    addLinks: [] | [Array<string>];
}> {
    return {
        categories: value.categories ? candid_some(value.categories) : candid_none(),
        removeMedia: value.removeMedia ? candid_some(await to_candid_vec_n10(uploadFile, downloadFile, value.removeMedia)) : candid_none(),
        updatePaywalledVideos: value.updatePaywalledVideos ? candid_some(await to_candid_vec_n42(uploadFile, downloadFile, value.updatePaywalledVideos)) : candid_none(),
        content: value.content ? candid_some(value.content) : candid_none(),
        removePublicVideos: value.removePublicVideos ? candid_some(await to_candid_vec_n10(uploadFile, downloadFile, value.removePublicVideos)) : candid_none(),
        reportReason: value.reportReason ? candid_some(value.reportReason) : candid_none(),
        removePaywallLinks: value.removePaywallLinks ? candid_some(value.removePaywallLinks) : candid_none(),
        removePaywalledVideos: value.removePaywalledVideos ? candid_some(await to_candid_vec_n10(uploadFile, downloadFile, value.removePaywalledVideos)) : candid_none(),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        addPublicVideos: value.addPublicVideos ? candid_some(await to_candid_vec_n10(uploadFile, downloadFile, value.addPublicVideos)) : candid_none(),
        updatePaywallLinks: value.updatePaywallLinks ? candid_some(to_candid_vec_n47(uploadFile, downloadFile, value.updatePaywallLinks)) : candid_none(),
        removeLinks: value.removeLinks ? candid_some(value.removeLinks) : candid_none(),
        addPaywallLinks: value.addPaywallLinks ? candid_some(value.addPaywallLinks) : candid_none(),
        addMedia: value.addMedia ? candid_some(await to_candid_vec_n10(uploadFile, downloadFile, value.addMedia)) : candid_none(),
        reportCategory: value.reportCategory ? candid_some(value.reportCategory) : candid_none(),
        addFileNames: value.addFileNames ? candid_some(value.addFileNames) : candid_none(),
        flagPost: value.flagPost ? candid_some(value.flagPost) : candid_none(),
        addPaywalledVideos: value.addPaywalledVideos ? candid_some(await to_candid_vec_n44(uploadFile, downloadFile, value.addPaywalledVideos)) : candid_none(),
        removeFileNames: value.removeFileNames ? candid_some(value.removeFileNames) : candid_none(),
        addLinks: value.addLinks ? candid_some(value.addLinks) : candid_none()
    };
}
async function to_candid_record_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paywalledVideos: Array<PaywalledVideo>;
    description?: string;
    isActive?: boolean;
    price?: bigint;
}): Promise<{
    paywalledVideos: Array<_PaywalledVideo>;
    description: [] | [string];
    isActive: [] | [boolean];
    price: [] | [bigint];
}> {
    return {
        paywalledVideos: await to_candid_vec_n44(uploadFile, downloadFile, value.paywalledVideos),
        description: value.description ? candid_some(value.description) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none()
    };
}
async function to_candid_record_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    description: string;
    isActive: boolean;
    price: bigint;
}): Promise<{
    blob: _ExternalBlob;
    description: string;
    isActive: boolean;
    price: bigint;
}> {
    return {
        blob: await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value.blob),
        description: value.description,
        isActive: value.isActive,
        price: value.price
    };
}
function to_candid_record_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description?: string;
    isActive?: boolean;
    price?: bigint;
    paywallLinks: Array<PaywallLink>;
}): {
    description: [] | [string];
    isActive: [] | [boolean];
    price: [] | [bigint];
    paywallLinks: Array<_PaywallLink>;
} {
    return {
        description: value.description ? candid_some(value.description) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none(),
        paywallLinks: value.paywallLinks
    };
}
function to_candid_variant_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(uploadFile, downloadFile, x)));
}
async function to_candid_vec_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    paywalledVideos: Array<PaywalledVideo>;
    description?: string;
    isActive?: boolean;
    price?: bigint;
}>): Promise<Array<{
    paywalledVideos: Array<_PaywalledVideo>;
    description: [] | [string];
    isActive: [] | [boolean];
    price: [] | [bigint];
}>> {
    return await Promise.all(value.map(async (x)=>await to_candid_record_n43(uploadFile, downloadFile, x)));
}
async function to_candid_vec_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PaywalledVideo>): Promise<Array<_PaywalledVideo>> {
    return await Promise.all(value.map(async (x)=>await to_candid_PaywalledVideo_n45(uploadFile, downloadFile, x)));
}
function to_candid_vec_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    description?: string;
    isActive?: boolean;
    price?: bigint;
    paywallLinks: Array<PaywallLink>;
}>): Array<{
    description: [] | [string];
    isActive: [] | [boolean];
    price: [] | [bigint];
    paywallLinks: Array<_PaywallLink>;
}> {
    return value.map((x)=>to_candid_record_n48(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
