/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Tip = IDL.Record({
  'transactionHash' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'tokenType' : IDL.Text,
  'amount' : IDL.Nat,
});
export const PaywalledVideo = IDL.Record({
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Nat,
});
export const PaywallLink = IDL.Record({
  'url' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'categories' : IDL.Vec(IDL.Text),
  'media' : IDL.Vec(ExternalBlob),
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'reportCount' : IDL.Nat,
  'ratingCount' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'tips' : IDL.Vec(Tip),
  'paywalledVideos' : IDL.Vec(PaywalledVideo),
  'author' : IDL.Principal,
  'links' : IDL.Vec(IDL.Text),
  'averageRating' : IDL.Float64,
  'fileNames' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'commentCount' : IDL.Nat,
  'reported' : IDL.Bool,
  'flagged' : IDL.Bool,
  'publicVideos' : IDL.Vec(ExternalBlob),
  'paywallLinks' : IDL.Vec(PaywallLink),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'totalRatings' : IDL.Nat,
  'newsletterSubscribed' : IDL.Bool,
  'accountId' : IDL.Text,
  'name' : IDL.Text,
  'averageRating' : IDL.Float64,
  'joinedDate' : Time,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'principalId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Wallet = IDL.Record({
  'balance' : IDL.Nat,
  'accountId' : IDL.Text,
  'owner' : IDL.Principal,
  'transactionHistory' : IDL.Vec(Tip),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const PostUpdatePayload = IDL.Record({
  'categories' : IDL.Opt(IDL.Vec(IDL.Text)),
  'removeMedia' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'updatePaywalledVideos' : IDL.Opt(
    IDL.Vec(
      IDL.Record({
        'paywalledVideos' : IDL.Vec(PaywalledVideo),
        'description' : IDL.Opt(IDL.Text),
        'isActive' : IDL.Opt(IDL.Bool),
        'price' : IDL.Opt(IDL.Nat),
      })
    )
  ),
  'content' : IDL.Opt(IDL.Text),
  'removePublicVideos' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'reportReason' : IDL.Opt(IDL.Text),
  'removePaywallLinks' : IDL.Opt(IDL.Vec(IDL.Text)),
  'removePaywalledVideos' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'addPublicVideos' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'updatePaywallLinks' : IDL.Opt(
    IDL.Vec(
      IDL.Record({
        'description' : IDL.Opt(IDL.Text),
        'isActive' : IDL.Opt(IDL.Bool),
        'price' : IDL.Opt(IDL.Nat),
        'paywallLinks' : IDL.Vec(PaywallLink),
      })
    )
  ),
  'removeLinks' : IDL.Opt(IDL.Vec(IDL.Text)),
  'addPaywallLinks' : IDL.Opt(IDL.Vec(PaywallLink)),
  'addMedia' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'reportCategory' : IDL.Opt(IDL.Text),
  'addFileNames' : IDL.Opt(IDL.Vec(IDL.Text)),
  'flagPost' : IDL.Opt(IDL.Bool),
  'addPaywalledVideos' : IDL.Opt(IDL.Vec(PaywalledVideo)),
  'removeFileNames' : IDL.Opt(IDL.Vec(IDL.Text)),
  'addLinks' : IDL.Opt(IDL.Vec(IDL.Text)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addToken' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanUpReports' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [Post],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'ensureWalletExists' : IDL.Func([], [], []),
  'flagPost' : IDL.Func([IDL.Nat], [], []),
  'getAccountId' : IDL.Func([], [IDL.Text], ['query']),
  'getAdminPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getBlob' : IDL.Func([ExternalBlob], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getImportedTokens' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPostById' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPostsByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getPostsByMediaType' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getPostsByPaywallStatus' : IDL.Func([IDL.Bool], [IDL.Vec(Post)], ['query']),
  'getPostsByTags' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Vec(Post)], ['query']),
  'getReportedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getSortedReportedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([], [Wallet], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'removeToken' : IDL.Func([IDL.Text], [], []),
  'reportPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPosts' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unflagPost' : IDL.Func([IDL.Nat], [], []),
  'updatePost' : IDL.Func([IDL.Nat, PostUpdatePayload], [Post], []),
  'uploadBlob' : IDL.Func([IDL.Vec(IDL.Nat8)], [ExternalBlob], []),
  'uploadBlobWithName' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Text],
      [ExternalBlob],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Tip = IDL.Record({
    'transactionHash' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'tokenType' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const PaywalledVideo = IDL.Record({
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const PaywallLink = IDL.Record({
    'url' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'categories' : IDL.Vec(IDL.Text),
    'media' : IDL.Vec(ExternalBlob),
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'reportCount' : IDL.Nat,
    'ratingCount' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'tips' : IDL.Vec(Tip),
    'paywalledVideos' : IDL.Vec(PaywalledVideo),
    'author' : IDL.Principal,
    'links' : IDL.Vec(IDL.Text),
    'averageRating' : IDL.Float64,
    'fileNames' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'commentCount' : IDL.Nat,
    'reported' : IDL.Bool,
    'flagged' : IDL.Bool,
    'publicVideos' : IDL.Vec(ExternalBlob),
    'paywallLinks' : IDL.Vec(PaywallLink),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'totalRatings' : IDL.Nat,
    'newsletterSubscribed' : IDL.Bool,
    'accountId' : IDL.Text,
    'name' : IDL.Text,
    'averageRating' : IDL.Float64,
    'joinedDate' : Time,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'principalId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Wallet = IDL.Record({
    'balance' : IDL.Nat,
    'accountId' : IDL.Text,
    'owner' : IDL.Principal,
    'transactionHistory' : IDL.Vec(Tip),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const PostUpdatePayload = IDL.Record({
    'categories' : IDL.Opt(IDL.Vec(IDL.Text)),
    'removeMedia' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'updatePaywalledVideos' : IDL.Opt(
      IDL.Vec(
        IDL.Record({
          'paywalledVideos' : IDL.Vec(PaywalledVideo),
          'description' : IDL.Opt(IDL.Text),
          'isActive' : IDL.Opt(IDL.Bool),
          'price' : IDL.Opt(IDL.Nat),
        })
      )
    ),
    'content' : IDL.Opt(IDL.Text),
    'removePublicVideos' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'reportReason' : IDL.Opt(IDL.Text),
    'removePaywallLinks' : IDL.Opt(IDL.Vec(IDL.Text)),
    'removePaywalledVideos' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'addPublicVideos' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'updatePaywallLinks' : IDL.Opt(
      IDL.Vec(
        IDL.Record({
          'description' : IDL.Opt(IDL.Text),
          'isActive' : IDL.Opt(IDL.Bool),
          'price' : IDL.Opt(IDL.Nat),
          'paywallLinks' : IDL.Vec(PaywallLink),
        })
      )
    ),
    'removeLinks' : IDL.Opt(IDL.Vec(IDL.Text)),
    'addPaywallLinks' : IDL.Opt(IDL.Vec(PaywallLink)),
    'addMedia' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'reportCategory' : IDL.Opt(IDL.Text),
    'addFileNames' : IDL.Opt(IDL.Vec(IDL.Text)),
    'flagPost' : IDL.Opt(IDL.Bool),
    'addPaywalledVideos' : IDL.Opt(IDL.Vec(PaywalledVideo)),
    'removeFileNames' : IDL.Opt(IDL.Vec(IDL.Text)),
    'addLinks' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addToken' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanUpReports' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [Post],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'ensureWalletExists' : IDL.Func([], [], []),
    'flagPost' : IDL.Func([IDL.Nat], [], []),
    'getAccountId' : IDL.Func([], [IDL.Text], ['query']),
    'getAdminPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getBlob' : IDL.Func(
        [ExternalBlob],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getImportedTokens' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPostById' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPostsByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getPostsByMediaType' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getPostsByPaywallStatus' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getPostsByTags' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getReportedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getSortedReportedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([], [Wallet], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'removeToken' : IDL.Func([IDL.Text], [], []),
    'reportPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPosts' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unflagPost' : IDL.Func([IDL.Nat], [], []),
    'updatePost' : IDL.Func([IDL.Nat, PostUpdatePayload], [Post], []),
    'uploadBlob' : IDL.Func([IDL.Vec(IDL.Nat8)], [ExternalBlob], []),
    'uploadBlobWithName' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Text],
        [ExternalBlob],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };