/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface PaywallLink {
  'url' : string,
  'description' : string,
  'isActive' : boolean,
  'price' : bigint,
}
export interface PaywalledVideo {
  'blob' : ExternalBlob,
  'description' : string,
  'isActive' : boolean,
  'price' : bigint,
}
export interface Post {
  'id' : bigint,
  'categories' : Array<string>,
  'media' : Array<ExternalBlob>,
  'likeCount' : bigint,
  'content' : string,
  'reportCount' : bigint,
  'ratingCount' : bigint,
  'tags' : Array<string>,
  'tips' : Array<Tip>,
  'paywalledVideos' : Array<PaywalledVideo>,
  'author' : Principal,
  'links' : Array<string>,
  'averageRating' : number,
  'fileNames' : Array<string>,
  'timestamp' : Time,
  'commentCount' : bigint,
  'reported' : boolean,
  'flagged' : boolean,
  'publicVideos' : Array<ExternalBlob>,
  'paywallLinks' : Array<PaywallLink>,
}
export interface PostUpdatePayload {
  'categories' : [] | [Array<string>],
  'removeMedia' : [] | [Array<ExternalBlob>],
  'updatePaywalledVideos' : [] | [
    Array<
      {
        'paywalledVideos' : Array<PaywalledVideo>,
        'description' : [] | [string],
        'isActive' : [] | [boolean],
        'price' : [] | [bigint],
      }
    >
  ],
  'content' : [] | [string],
  'removePublicVideos' : [] | [Array<ExternalBlob>],
  'reportReason' : [] | [string],
  'removePaywallLinks' : [] | [Array<string>],
  'removePaywalledVideos' : [] | [Array<ExternalBlob>],
  'tags' : [] | [Array<string>],
  'addPublicVideos' : [] | [Array<ExternalBlob>],
  'updatePaywallLinks' : [] | [
    Array<
      {
        'description' : [] | [string],
        'isActive' : [] | [boolean],
        'price' : [] | [bigint],
        'paywallLinks' : Array<PaywallLink>,
      }
    >
  ],
  'removeLinks' : [] | [Array<string>],
  'addPaywallLinks' : [] | [Array<PaywallLink>],
  'addMedia' : [] | [Array<ExternalBlob>],
  'reportCategory' : [] | [string],
  'addFileNames' : [] | [Array<string>],
  'flagPost' : [] | [boolean],
  'addPaywalledVideos' : [] | [Array<PaywalledVideo>],
  'removeFileNames' : [] | [Array<string>],
  'addLinks' : [] | [Array<string>],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface Tip {
  'transactionHash' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'tokenType' : string,
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'totalRatings' : bigint,
  'newsletterSubscribed' : boolean,
  'accountId' : string,
  'name' : string,
  'averageRating' : number,
  'joinedDate' : Time,
  'followerCount' : bigint,
  'followingCount' : bigint,
  'profilePicture' : [] | [ExternalBlob],
  'principalId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'balance' : bigint,
  'accountId' : string,
  'owner' : Principal,
  'transactionHistory' : Array<Tip>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addToken' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanUpReports' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPost' : ActorMethod<
    [
      string,
      Array<ExternalBlob>,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    Post
  >,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'ensureWalletExists' : ActorMethod<[], undefined>,
  'flagPost' : ActorMethod<[bigint], undefined>,
  'getAccountId' : ActorMethod<[], string>,
  'getAdminPosts' : ActorMethod<[], Array<Post>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getBlob' : ActorMethod<[ExternalBlob], [] | [Uint8Array]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getImportedTokens' : ActorMethod<[], Array<string>>,
  'getPost' : ActorMethod<[bigint], Post>,
  'getPostById' : ActorMethod<[bigint], Post>,
  'getPostsByAuthor' : ActorMethod<[Principal], Array<Post>>,
  'getPostsByCategory' : ActorMethod<[string], Array<Post>>,
  'getPostsByMediaType' : ActorMethod<[string], Array<Post>>,
  'getPostsByPaywallStatus' : ActorMethod<[boolean], Array<Post>>,
  'getPostsByTags' : ActorMethod<[Array<string>], Array<Post>>,
  'getReportedPosts' : ActorMethod<[], Array<Post>>,
  'getSortedReportedPosts' : ActorMethod<[], Array<Post>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[], Wallet>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'removeToken' : ActorMethod<[string], undefined>,
  'reportPost' : ActorMethod<[bigint, string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPosts' : ActorMethod<[string, boolean, boolean], Array<Post>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unflagPost' : ActorMethod<[bigint], undefined>,
  'updatePost' : ActorMethod<[bigint, PostUpdatePayload], Post>,
  'uploadBlob' : ActorMethod<[Uint8Array], ExternalBlob>,
  'uploadBlobWithName' : ActorMethod<[Uint8Array, string], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];