/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserPublic {
    bio: string;
    username: string;
    createdAt: bigint;
    avatarUrl: string;
    isAdmin: boolean;
    principalId: string;
}
export interface PostPublic {
    id: bigint;
    deleted: boolean;
    content: string;
    authorId: string;
    createdAt: bigint;
    authorName: string;
    imageUrl?: string;
    flagged: boolean;
}
export interface backendInterface {
    createPost(content: string, imageUrl: string | null): Promise<PostPublic>;
    deletePost(postId: bigint): Promise<void>;
    deleteUser(principalId: string): Promise<void>;
    editPost(postId: bigint, content: string, imageUrl: string | null): Promise<PostPublic>;
    flagPost(postId: bigint): Promise<void>;
    getAllPostsAdmin(): Promise<Array<PostPublic>>;
    getFlaggedPosts(): Promise<Array<PostPublic>>;
    getPost(postId: bigint): Promise<PostPublic | null>;
    getPosts(page: bigint, pageSize: bigint): Promise<Array<PostPublic>>;
    getUserProfile(principalId: string): Promise<UserPublic | null>;
    getUsers(): Promise<Array<UserPublic>>;
    isAdmin(): Promise<boolean>;
    registerOrGetUser(): Promise<UserPublic>;
    unflagPost(postId: bigint): Promise<void>;
    updateProfile(username: string, bio: string, avatarUrl: string): Promise<UserPublic>;
}
import type { PostPublic as _PostPublic, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createPost(arg0: string, arg1: string | null): Promise<PostPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PostPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PostPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async editPost(arg0: bigint, arg1: string, arg2: string | null): Promise<PostPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.editPost(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PostPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPost(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PostPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async flagPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagPost(arg0);
            return result;
        }
    }
    async getAllPostsAdmin(): Promise<Array<PostPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPostsAdmin();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPostsAdmin();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlaggedPosts(): Promise<Array<PostPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlaggedPosts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlaggedPosts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<PostPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosts(arg0: bigint, arg1: bigint): Promise<Array<PostPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts(arg0, arg1);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts(arg0, arg1);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: string): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async registerOrGetUser(): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrGetUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrGetUser();
            return result;
        }
    }
    async unflagPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unflagPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unflagPost(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_PostPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostPublic): PostPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostPublic]): PostPublic | null {
    return value.length === 0 ? null : from_candid_PostPublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    deleted: boolean;
    content: string;
    authorId: string;
    createdAt: bigint;
    authorName: string;
    imageUrl: [] | [string];
    flagged: boolean;
}): {
    id: bigint;
    deleted: boolean;
    content: string;
    authorId: string;
    createdAt: bigint;
    authorName: string;
    imageUrl?: string;
    flagged: boolean;
} {
    return {
        id: value.id,
        deleted: value.deleted,
        content: value.content,
        authorId: value.authorId,
        createdAt: value.createdAt,
        authorName: value.authorName,
        imageUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.imageUrl)),
        flagged: value.flagged
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostPublic>): Array<PostPublic> {
    return value.map((x)=>from_candid_PostPublic_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
